In [1]:
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt 
from datetime import datetime
import datetime 
import time 
import collections 
import pandas as pd
import numpy as np
from matplotlib import colors
from matplotlib import cm 
import os 
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

In [2]:
df = pd.read_csv('bierstadter.csv')

In [3]:
# Convert the timestamp column to datetime objects
df['Datetime'] = pd.to_datetime(df['Timestamp'], unit='ms')

# Set the starting date to November 22, 2022
start_date = pd.to_datetime('2022-11-22')

# Add the starting date to the datetime objects
df['Datetime'] = start_date + (df['Datetime'] - df['Datetime'].min())


# Print the resulting DataFrame
print(df)

          DeviceId      Timestamp      X      Y                Datetime
0       1000501442  1669126573166   6329   8497 2022-11-22 00:00:39.820
1       2047000004  1676658279470  57739  28319 2023-02-17 04:09:06.124
2       2047000004  1676658277456  58123  26368 2023-02-17 04:09:04.110
3       2047000004  1676658276456  58382  25273 2023-02-17 04:09:03.110
4       2047000004  1676658275440  58794  24830 2023-02-17 04:09:02.094
...            ...            ...    ...    ...                     ...
897349  2047000853  1675076611670  57624  30189 2023-01-29 20:47:58.324
897350  2047000853  1675076610960  57950  30761 2023-01-29 20:47:57.614
897351  2047000853  1675076609293  57305  32050 2023-01-29 20:47:55.947
897352  2047000853  1675076608763  58303  32221 2023-01-29 20:47:55.417
897353  2236000001  1669126533346 -44023  10527 2022-11-22 00:00:00.000

[897354 rows x 5 columns]

In [4]:
df = df.loc[df['Datetime'].dt.date != pd.to_datetime('2022-11-22').date()]
#df

In [5]:
bss=pd.read_excel('bss.xlsx')
#bss

In [6]:
df[['X', 'Y']] = df[['X', 'Y']].div(1000)

In [7]:
import pandas as pd


for i, row in df.iterrows():
    x, y = row['X'], row['Y']
    for j, row2 in bss.iterrows():
        if row2['minX'] <= x <= row2['maxX'] and row2['minY'] <= y <= row2['maxY']:
            df.loc[i, 'area'] = row2['areasPermanentId']
            break

In [8]:
df['area'].fillna(111, inplace=True)
df

,DeviceId,Timestamp,X,Y,Datetime,area
1,2047000004,1676658279470,57.739,28.319,2023-02-17 04:09:06.124,111.0
2,2047000004,1676658277456,58.123,26.368,2023-02-17 04:09:04.110,111.0
3,2047000004,1676658276456,58.382,25.273,2023-02-17 04:09:03.110,1364.0
4,2047000004,1676658275440,58.794,24.830,2023-02-17 04:09:02.094,1364.0
5,2047000004,1676658273436,59.283,24.631,2023-02-17 04:09:00.090,1364.0
...,...,...,...,...,...,...
897348,2047000853,1675076612513,57.517,29.264,2023-01-29 20:47:59.167,111.0
897349,2047000853,1675076611670,57.624,30.189,2023-01-29 20:47:58.324,111.0
897350,2047000853,1675076610960,57.950,30.761,2023-01-29 20:47:57.614,111.0
897351,2047000853,1675076609293,57.305,32.050,2023-01-29 20:47:55.947,111.0
897352,2047000853,1675076608763,58.303,32.221,2023-01-29 20:47:55.417,111.0

In [70]:
df['idTblLoc'] = 3

In [71]:
start_time = '2023-01-30'
end_time = '2023-01-31'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
#print(df_filtered)

In [72]:
df_filtered

,DeviceId,Timestamp,X,Y,Datetime,area,idTblLoc,path_id
3201,2047000054,1675090925833,56.713,30.057,2023-01-30 00:46:32.487,111.0,3,1
3200,2047000054,1675090949930,56.750,29.949,2023-01-30 00:46:56.584,111.0,3,1
3199,2047000054,1675091072133,58.196,30.252,2023-01-30 00:48:58.787,111.0,3,1
3198,2047000054,1675091099753,58.570,30.000,2023-01-30 00:49:26.407,111.0,3,1
3197,2047000054,1675091121896,55.127,24.376,2023-01-30 00:49:48.550,1390.0,3,1
...,...,...,...,...,...,...,...,...
28319,2047000853,1675174389456,67.480,25.904,2023-01-30 23:57:36.110,1364.0,3,1863
28318,2047000853,1675174390473,67.032,25.205,2023-01-30 23:57:37.127,1364.0,3,1864
28317,2047000853,1675174391466,67.410,25.590,2023-01-30 23:57:38.120,1364.0,3,1865
28316,2047000853,1675174391996,67.059,25.187,2023-01-30 23:57:38.650,1364.0,3,1866
28315,2047000853,1675174418700,66.849,24.889,2023-01-30 23:58:05.354,1364.0,3,1867

In [73]:
df_filtered.to_csv('bss1.csv', index=False)

In [74]:
start_time = '2023-01-31'
end_time = '2023-02-01'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
1585   2047000074  1675247643316  57.112  30.834 2023-01-31 20:18:29.970
1584   2047000074  1675247644073  57.039  29.868 2023-01-31 20:18:30.727
1583   2047000074  1675247644576  57.337  29.263 2023-01-31 20:18:31.230
1582   2047000074  1675247645086  58.090  28.830 2023-01-31 20:18:31.740
1581   2047000074  1675247645590  57.576  28.727 2023-01-31 20:18:32.244
...           ...            ...     ...     ...                     ...
20655  2047000853  1675260792613  65.372  23.597 2023-01-31 23:57:39.267
20654  2047000853  1675260793113  64.555  23.082 2023-01-31 23:57:39.767
20653  2047000853  1675260795633  65.219  23.352 2023-01-31 23:57:42.287
20652  2047000853  1675260796136  64.474  23.398 2023-01-31 23:57:42.790
20651  2047000853  1675260822863  64.505  23.452 2023-01-31 23:58:09.517

         area  idTblLoc  path_id
1585    111.0         3        1
1584    111.0         3        1
1583    111.0         3        1
1582    111.0         3        1
1581    111.0         3        1
...       ...       ...      ...
20655  1364.0         3     1182
20654  1364.0         3     1183
20653  1364.0         3     1184
20652  1364.0         3     1185
20651  1364.0         3     1186

[22937 rows x 8 columns]

In [75]:
df_filtered.to_csv('bss2.csv', index=False)

In [76]:
start_time = '2023-02-01'
end_time = '2023-02-02'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
776    2047000012  1675333436273  57.022  33.403 2023-02-01 20:08:22.927
775    2047000012  1675333438790  57.717  33.175 2023-02-01 20:08:25.444
774    2047000012  1675333439270  58.808  33.444 2023-02-01 20:08:25.924
773    2047000012  1675333439786  57.994  32.988 2023-02-01 20:08:26.440
772    2047000012  1675333440796  57.688  33.090 2023-02-01 20:08:27.450
...           ...            ...     ...     ...                     ...
34140  2047000853  1675335496606  58.417  28.096 2023-02-01 20:42:43.260
34139  2047000853  1675335497116  57.574  29.020 2023-02-01 20:42:43.770
34138  2047000853  1675335497620  57.768  29.723 2023-02-01 20:42:44.274
34137  2047000853  1675335499636  57.170  31.375 2023-02-01 20:42:46.290
34136  2047000853  1675335500133  58.529  31.867 2023-02-01 20:42:46.787

        area  idTblLoc  path_id
776    111.0         3        1
775    111.0         3        1
774    111.0         3        1
773    111.0         3        1
772    111.0         3        1
...      ...       ...      ...
34140  111.0         3     2138
34139  111.0         3     2138
34138  111.0         3     2138
34137  111.0         3     2138
34136  111.0         3     2138

[36085 rows x 8 columns]

In [77]:
df_filtered.to_csv('bss3.csv', index=False)

In [78]:
start_time = '2023-02-02'
end_time = '2023-02-03'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
817    2047000012  1675353637976  57.377  31.598 2023-02-02 01:45:04.630
816    2047000012  1675353638480  57.264  31.064 2023-02-02 01:45:05.134
815    2047000012  1675353638996  59.221  30.494 2023-02-02 01:45:05.650
814    2047000012  1675353640006  57.620  28.779 2023-02-02 01:45:06.660
813    2047000012  1675353640606  58.193  27.647 2023-02-02 01:45:07.260
...           ...            ...     ...     ...                     ...
50496  2047000466  1675433718686  41.126  13.636 2023-02-02 23:59:45.340
50495  2047000466  1675433720200  41.288  13.031 2023-02-02 23:59:46.854
50494  2047000466  1675433722710  41.606  13.583 2023-02-02 23:59:49.364
50493  2047000466  1675433726243  41.257  13.100 2023-02-02 23:59:52.897
50492  2047000466  1675433732796  42.048  12.988 2023-02-02 23:59:59.450

        area  idTblLoc  path_id
817    111.0         3        1
816    111.0         3        1
815    111.0         3        1
814    111.0         3        1
813    111.0         3        1
...      ...       ...      ...
50496  111.0         3     3210
50495  111.0         3     3210
50494  111.0         3     3210
50493  111.0         3     3210
50492  111.0         3     3210

[54306 rows x 8 columns]

In [79]:
df_filtered.to_csv('bss4.csv', index=False)

In [80]:
start_time = '2023-02-03'
end_time = '2023-02-04'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
469    2047000012  1675514584513  57.608  31.527 2023-02-03 22:27:31.167
468    2047000012  1675514587040  57.052  32.028 2023-02-03 22:27:33.694
467    2047000012  1675514587600  57.161  31.347 2023-02-03 22:27:34.254
466    2047000012  1675514588573  57.364  30.230 2023-02-03 22:27:35.227
465    2047000012  1675514589163  57.863  31.151 2023-02-03 22:27:35.817
...           ...            ...     ...     ...                     ...
42371  2047000853  1675519125153  64.564  23.871 2023-02-03 23:43:11.807
42370  2047000853  1675519135743  64.631  23.361 2023-02-03 23:43:22.397
42369  2047000853  1675519140770  64.180  23.916 2023-02-03 23:43:27.424
42368  2047000853  1675519141280  64.640  23.535 2023-02-03 23:43:27.934
42367  2047000853  1675519167023  64.609  23.535 2023-02-03 23:43:53.677

         area  idTblLoc  path_id
469     111.0         3        1
468     111.0         3        1
467     111.0         3        1
466     111.0         3        1
465     111.0         3        1
...       ...       ...      ...
42371  1364.0         3     2786
42370  1364.0         3     2787
42369  1364.0         3     2788
42368  1364.0         3     2789
42367  1364.0         3     2790

[45413 rows x 8 columns]

In [81]:
df_filtered.to_csv('bss5.csv', index=False)

In [82]:
start_time = '2023-02-04'
end_time = '2023-02-05'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
2540   2047000012  1675520403496  61.054  12.707 2023-02-04 00:04:30.150
2539   2047000012  1675520404420  60.813  13.510 2023-02-04 00:04:31.074
2538   2047000012  1675520404930  60.599  13.968 2023-02-04 00:04:31.584
2537   2047000012  1675520405940  60.362  14.665 2023-02-04 00:04:32.594
2536   2047000012  1675520406433  60.121  15.199 2023-02-04 00:04:33.087
...           ...            ...     ...     ...                     ...
19428  2047000853  1675533098453  58.938  27.202 2023-02-04 03:36:05.107
19427  2047000853  1675533098963  58.273  27.454 2023-02-04 03:36:05.617
19426  2047000853  1675533099463  58.585  27.935 2023-02-04 03:36:06.117
19425  2047000853  1675533100463  58.394  29.608 2023-02-04 03:36:07.117
19424  2047000853  1675533100973  57.417  30.390 2023-02-04 03:36:07.627

         area  idTblLoc  path_id
2540    111.0         3        1
2539   1362.0         3        1
2538   1362.0         3        1
2537   1362.0         3        1
2536   1362.0         3        1
...       ...       ...      ...
19428  1364.0         3     1548
19427   111.0         3     1548
19426   111.0         3     1548
19425   111.0         3     1548
19424   111.0         3     1548

[20264 rows x 8 columns]

In [83]:
df_filtered.to_csv('bss6.csv', index=False)

In [84]:
start_time = '2023-02-05'
end_time = '2023-02-06'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
1456   2047000012  1675669920026  58.591  28.262 2023-02-05 17:36:26.680
1455   2047000012  1675669920763  57.117  28.050 2023-02-05 17:36:27.417
1454   2047000012  1675669921506  57.571  26.440 2023-02-05 17:36:28.160
1453   2047000012  1675669926343  55.577  21.105 2023-02-05 17:36:32.997
1452   2047000012  1675669927716  55.506  21.931 2023-02-05 17:36:34.370
...           ...            ...     ...     ...                     ...
15660  2047000853  1675692582880  19.753  29.028 2023-02-05 23:54:09.534
15659  2047000853  1675692591456  15.785  29.858 2023-02-05 23:54:18.110
15658  2047000853  1675692592016  16.819  30.420 2023-02-05 23:54:18.670
15657  2047000853  1675692620683  16.522  29.972 2023-02-05 23:54:47.337
15656  2047000853  1675692622200  16.469  29.956 2023-02-05 23:54:48.854

         area  idTblLoc  path_id
1456    111.0         3        1
1455    111.0         3        1
1454    111.0         3        1
1453   1390.0         3        1
1452   1390.0         3        1
...       ...       ...      ...
15660   111.0         3      933
15659   111.0         3      933
15658   111.0         3      933
15657   111.0         3      933
15656   111.0         3      933

[17907 rows x 8 columns]

In [85]:
df_filtered.to_csv('bss7.csv', index=False)

In [86]:
start_time = '2023-02-06'
end_time = '2023-02-07'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
1968   2047000012  1675698294020  57.226  33.521 2023-02-06 01:29:20.674
1967   2047000012  1675698295540  57.161  32.217 2023-02-06 01:29:22.194
1966   2047000012  1675698296536  57.267  30.919 2023-02-06 01:29:23.190
1965   2047000012  1675698298563  57.428  29.676 2023-02-06 01:29:25.217
1964   2047000012  1675698300570  57.019  29.349 2023-02-06 01:29:27.224
...           ...            ...     ...     ...                     ...
33624  2047000853  1675700675453  38.486  30.428 2023-02-06 02:09:02.107
33623  2047000853  1675700675943  38.667  29.676 2023-02-06 02:09:02.597
33622  2047000853  1675700676446  38.424  30.268 2023-02-06 02:09:03.100
33621  2047000853  1675700676960  38.554  29.695 2023-02-06 02:09:03.614
33620  2047000853  1675700702660  38.535  29.812 2023-02-06 02:09:29.314

        area  idTblLoc  path_id
1968   111.0         3        1
1967   111.0         3        1
1966   111.0         3        1
1965   111.0         3        1
1964   111.0         3        1
...      ...       ...      ...
33624  111.0         3     2075
33623  111.0         3     2075
33622  111.0         3     2075
33621  111.0         3     2075
33620  111.0         3     2075

[34442 rows x 8 columns]

In [87]:
df_filtered.to_csv('bss8.csv', index=False)

In [88]:
start_time = '2023-02-07'
end_time = '2023-02-08'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
3689   2047000032  1675779818256  57.757  27.199 2023-02-07 00:08:04.910
3688   2047000032  1675779818753  57.337  26.920 2023-02-07 00:08:05.407
3687   2047000032  1675779827736  54.490  20.441 2023-02-07 00:08:14.390
3686   2047000032  1675779831763  53.844  18.309 2023-02-07 00:08:18.417
3685   2047000032  1675779832703  53.191  17.721 2023-02-07 00:08:19.357
...           ...            ...     ...     ...                     ...
28123  2047000853  1675858107116  64.222  23.508 2023-02-07 21:52:53.770
28122  2047000853  1675858114176  64.617  22.794 2023-02-07 21:53:00.830
28121  2047000853  1675858117196  64.246  23.170 2023-02-07 21:53:03.850
28120  2047000853  1675858146433  64.312  23.244 2023-02-07 21:53:33.087
28119  2047000853  1675858235146  64.368  23.358 2023-02-07 21:55:01.800

         area  idTblLoc  path_id
3689    111.0         3        1
3688    111.0         3        1
3687   1390.0         3        1
3686   1390.0         3        1
3685   1390.0         3        1
...       ...       ...      ...
28123  1364.0         3     1904
28122  1364.0         3     1905
28121  1364.0         3     1906
28120  1364.0         3     1907
28119  1364.0         3     1908

[29485 rows x 8 columns]

In [89]:
df_filtered.to_csv('bss9.csv', index=False)

In [90]:
start_time = '2023-02-08'
end_time = '2023-02-09'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
40     2047000012  1675942574583  57.675  26.239 2023-02-08 21:20:41.237
39     2047000012  1675942576966  57.558  25.720 2023-02-08 21:20:43.620
38     2047000012  1675942587036  54.746  19.798 2023-02-08 21:20:53.690
37     2047000012  1675942587543  54.486  19.099 2023-02-08 21:20:54.197
36     2047000012  1675942588510  53.906  18.125 2023-02-08 21:20:55.164
...           ...            ...     ...     ...                     ...
28708  2047000853  1675952095800  62.732  28.651 2023-02-08 23:59:22.454
28707  2047000853  1675952097393  62.136  28.182 2023-02-08 23:59:24.047
28706  2047000853  1675952100833  62.858  28.516 2023-02-08 23:59:27.487
28705  2047000853  1675952101340  62.355  27.893 2023-02-08 23:59:27.994
28704  2047000853  1675952128553  62.066  28.144 2023-02-08 23:59:55.207

         area  idTblLoc  path_id
40      111.0         3        1
39     1363.0         3        1
38     1390.0         3        1
37     1390.0         3        1
36     1390.0         3        1
...       ...       ...      ...
28708   111.0         3     1836
28707   111.0         3     1836
28706   111.0         3     1836
28705  1364.0         3     1837
28704   111.0         3     1837

[31084 rows x 8 columns]

In [91]:
df_filtered.to_csv('bss10.csv', index=False)

In [92]:
start_time = '2023-02-09'
end_time = '2023-02-10'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
232    2047000012  1676025128116  58.216  28.520 2023-02-09 20:16:34.770
231    2047000012  1676025128623  57.098  29.145 2023-02-09 20:16:35.277
230    2047000012  1676025129130  57.705  27.841 2023-02-09 20:16:35.784
229    2047000012  1676025129633  57.100  28.242 2023-02-09 20:16:36.287
228    2047000012  1676025130746  57.705  26.785 2023-02-09 20:16:37.400
...           ...            ...     ...     ...                     ...
50483  2047000853  1676015794136  25.274  22.214 2023-02-09 17:41:00.790
50482  2047000853  1676016403236  45.908   5.138 2023-02-09 17:51:09.890
50481  2047000853  1676016405753  45.908   4.368 2023-02-09 17:51:12.407
50480  2047000853  1676016446586  46.227   4.874 2023-02-09 17:51:53.240
50479  2047000853  1676016472296  46.030   4.668 2023-02-09 17:52:18.950

        area  idTblLoc  path_id
232    111.0         3        1
231    111.0         3        1
230    111.0         3        1
229    111.0         3        1
228    111.0         3        1
...      ...       ...      ...
50483  111.0         3     3921
50482  111.0         3     3921
50481  111.0         3     3921
50480  111.0         3     3921
50479  111.0         3     3921

[51206 rows x 8 columns]

In [93]:
df_filtered.to_csv('bss11.csv', index=False)

In [94]:
start_time = '2023-02-10'
end_time = '2023-02-11'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

          DeviceId      Timestamp       X       Y                Datetime  \
4971    2047000022  1676100277766  57.786  26.001 2023-02-10 17:09:04.420
4970    2047000022  1676100283760  52.900  23.535 2023-02-10 17:09:10.414
4969    2047000022  1676100284270  52.640  23.468 2023-02-10 17:09:10.924
4968    2047000022  1676100284766  52.381  23.533 2023-02-10 17:09:11.420
4967    2047000022  1676100285270  51.887  23.423 2023-02-10 17:09:11.924
...            ...            ...     ...     ...                     ...
103449  2047000853  1676099062206   8.275  16.038 2023-02-10 16:48:48.860
103448  2047000853  1676099088406   8.240  16.791 2023-02-10 16:49:15.060
103447  2047000853  1676099167563   8.464  16.091 2023-02-10 16:50:34.217
103446  2047000853  1676099223010   8.247  16.760 2023-02-10 16:51:29.664
103445  2047000853  1676099413063   8.461  16.116 2023-02-10 16:54:39.717

          area  idTblLoc  path_id
4971     111.0         3        1
4970    1390.0         3        1
4969    1390.0         3        1
4968    1390.0         3        1
4967    1390.0         3        1
...        ...       ...      ...
103449   111.0         3     6137
103448   111.0         3     6137
103447   111.0         3     6137
103446   111.0         3     6137
103445   111.0         3     6137

[103682 rows x 8 columns]

In [95]:
df_filtered.to_csv('bss12.csv', index=False)

In [96]:
start_time = '2023-02-11'
end_time = '2023-02-12'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
597    2047000012  1676131293916  56.785  32.417 2023-02-11 01:46:00.570
596    2047000012  1676131294936  56.822  31.741 2023-02-11 01:46:01.590
595    2047000012  1676131295936  56.842  30.442 2023-02-11 01:46:02.590
594    2047000012  1676131296440  57.161  29.805 2023-02-11 01:46:03.094
593    2047000012  1676131297456  57.256  29.229 2023-02-11 01:46:04.110
...           ...            ...     ...     ...                     ...
35018  2047000457  1676140679703  58.281  27.268 2023-02-11 04:22:26.357
35017  2047000457  1676140680690  57.935  27.907 2023-02-11 04:22:27.344
35016  2047000457  1676140681240  57.912  28.358 2023-02-11 04:22:27.894
35015  2047000457  1676140681723  57.774  29.103 2023-02-11 04:22:28.377
35014  2047000457  1676140682760  58.085  30.664 2023-02-11 04:22:29.414

        area  idTblLoc  path_id
597    111.0         3        1
596    111.0         3        1
595    111.0         3        1
594    111.0         3        1
593    111.0         3        1
...      ...       ...      ...
35018  111.0         3     2334
35017  111.0         3     2334
35016  111.0         3     2334
35015  111.0         3     2334
35014  111.0         3     2334

[36990 rows x 8 columns]

In [97]:
df_filtered.to_csv('bss13.csv', index=False)

In [98]:
start_time = '2023-02-12'
end_time = '2023-02-13'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
2568   2047000032  1676284634540  56.904  33.953 2023-02-12 20:21:41.194
2567   2047000032  1676284636076  57.043  33.417 2023-02-12 20:21:42.730
2566   2047000032  1676284637100  57.422  32.882 2023-02-12 20:21:43.754
2565   2047000032  1676284637596  57.425  32.261 2023-02-12 20:21:44.250
2564   2047000032  1676284638833  57.076  31.726 2023-02-12 20:21:45.487
...           ...            ...     ...     ...                     ...
43971  2047000853  1676283909000  12.586  16.504 2023-02-12 20:09:35.654
43970  2047000853  1676286813520  10.952  15.410 2023-02-12 20:58:00.174
43969  2047000853  1676286814093  10.778  14.612 2023-02-12 20:58:00.747
43968  2047000853  1676286814760  10.816  13.990 2023-02-12 20:58:01.414
43967  2047000853  1676286819756  11.430  13.939 2023-02-12 20:58:06.410

        area  idTblLoc  path_id
2568   111.0         3        1
2567   111.0         3        1
2566   111.0         3        1
2565   111.0         3        1
2564   111.0         3        1
...      ...       ...      ...
43971  111.0         3     2722
43970  111.0         3     2722
43969  111.0         3     2722
43968  111.0         3     2722
43967  111.0         3     2722

[44055 rows x 8 columns]

In [99]:
df_filtered.to_csv('bss14.csv', index=False)

In [100]:
start_time = '2023-02-13'
end_time = '2023-02-14'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
3312   2047000012  1676305212110  57.214  30.172 2023-02-13 02:04:38.764
3311   2047000012  1676305212850  56.758  29.876 2023-02-13 02:04:39.504
3310   2047000012  1676305214866  57.302  28.962 2023-02-13 02:04:41.520
3309   2047000012  1676305215906  57.607  28.433 2023-02-13 02:04:42.560
3308   2047000012  1676305216903  57.687  27.921 2023-02-13 02:04:43.557
...           ...            ...     ...     ...                     ...
61401  2047000853  1676378743986  14.420  18.443 2023-02-13 22:30:10.640
61400  2047000853  1676378745003  13.031  17.879 2023-02-13 22:30:11.657
61399  2047000853  1676378751466  12.874  17.633 2023-02-13 22:30:18.120
61398  2047000853  1676378811696  10.461  16.870 2023-02-13 22:31:18.350
61397  2047000853  1676378812720  10.885  15.075 2023-02-13 22:31:19.374

        area  idTblLoc  path_id
3312   111.0         3        1
3311   111.0         3        1
3310   111.0         3        1
3309   111.0         3        1
3308   111.0         3        1
...      ...       ...      ...
61401  111.0         3     3805
61400  111.0         3     3805
61399  111.0         3     3805
61398  111.0         3     3805
61397  111.0         3     3805

[61541 rows x 8 columns]

In [101]:
df_filtered.to_csv('bss15.csv', index=False)

In [102]:
start_time = '2023-02-14'
end_time = '2023-02-15'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
1882   2047000022  1676385716806  57.549  33.374 2023-02-14 00:26:23.460
1881   2047000022  1676385717793  56.996  32.690 2023-02-14 00:26:24.447
1880   2047000022  1676385722326  57.318  31.155 2023-02-14 00:26:28.980
1879   2047000022  1676385725460  57.704  30.655 2023-02-14 00:26:32.114
1878   2047000022  1676385731393  58.022  29.108 2023-02-14 00:26:38.047
...           ...            ...     ...     ...                     ...
57421  2047000853  1676446842100   9.883  13.796 2023-02-14 17:25:08.754
57420  2047000853  1676446855766  11.009  11.601 2023-02-14 17:25:22.420
57419  2047000853  1676446856303  10.962  12.447 2023-02-14 17:25:22.957
57418  2047000853  1676446859243  10.878  13.150 2023-02-14 17:25:25.897
57417  2047000853  1676446861263  10.156  16.184 2023-02-14 17:25:27.917

        area  idTblLoc  path_id
1882   111.0         3        1
1881   111.0         3        1
1880   111.0         3        1
1879   111.0         3        1
1878   111.0         3        1
...      ...       ...      ...
57421  111.0         3     3528
57420  111.0         3     3528
57419  111.0         3     3528
57418  111.0         3     3528
57417  111.0         3     3528

[57422 rows x 8 columns]

In [103]:
df_filtered.to_csv('bss16.csv', index=False)

In [104]:
start_time = '2023-02-15'
end_time = '2023-02-16'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
2399   2047000012  1676540067670  57.114  28.216 2023-02-15 19:18:54.324
2398   2047000012  1676540068696  57.650  27.832 2023-02-15 19:18:55.350
2397   2047000012  1676540070470  57.733  27.200 2023-02-15 19:18:57.124
2396   2047000012  1676540071980  57.222  26.080 2023-02-15 19:18:58.634
2395   2047000012  1676540073796  56.870  25.449 2023-02-15 19:19:00.450
...           ...            ...     ...     ...                     ...
63053  2047000853  1676556913413  33.923  12.014 2023-02-15 23:59:40.067
63052  2047000853  1676556916440  33.804  12.506 2023-02-15 23:59:43.094
63051  2047000853  1676556921473  33.863  11.785 2023-02-15 23:59:48.127
63050  2047000853  1676556923516  33.601  13.035 2023-02-15 23:59:50.170
63049  2047000853  1676556926520  33.352  13.556 2023-02-15 23:59:53.174

         area  idTblLoc  path_id
2399    111.0         3        1
2398    111.0         3        1
2397    111.0         3        1
2396   1363.0         3        1
2395   1363.0         3        1
...       ...       ...      ...
63053   111.0         3     3924
63052   111.0         3     3924
63051   111.0         3     3924
63050   111.0         3     3924
63049   111.0         3     3924

[64356 rows x 8 columns]

In [105]:
df_filtered.to_csv('bss17.csv', index=False)

In [106]:
start_time = '2023-02-16'
end_time = '2023-02-17'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
673    2047000004  1676627639713  57.508  28.648 2023-02-16 19:38:26.367
672    2047000004  1676627640700  57.766  28.318 2023-02-16 19:38:27.354
671    2047000004  1676627641406  57.725  27.306 2023-02-16 19:38:28.060
670    2047000004  1676627642420  57.574  26.423 2023-02-16 19:38:29.074
669    2047000004  1676627642950  57.336  25.865 2023-02-16 19:38:29.604
...           ...            ...     ...     ...                     ...
94458  2047000853  1676643271763  60.012  24.431 2023-02-16 23:58:58.417
94457  2047000853  1676643273760  59.035  25.384 2023-02-16 23:59:00.414
94456  2047000853  1676643274803  58.576  25.759 2023-02-16 23:59:01.457
94455  2047000853  1676643282846  58.254  27.392 2023-02-16 23:59:09.500
94454  2047000853  1676643283846  57.815  27.819 2023-02-16 23:59:10.500

         area  idTblLoc  path_id
673     111.0         3        1
672     111.0         3        1
671     111.0         3        1
670     111.0         3        1
669    1363.0         3        1
...       ...       ...      ...
94458  1364.0         3     6447
94457  1364.0         3     6448
94456  1364.0         3     6449
94455   111.0         3     6449
94454   111.0         3     6449

[99164 rows x 8 columns]

In [107]:
df_filtered.to_csv('bss18.csv', index=False)

In [108]:
start_time = '2023-02-17'
end_time = '2023-02-18'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
603    2047000004  1676653022986  57.097  30.224 2023-02-17 02:41:29.640
602    2047000004  1676653025653  57.293  28.114 2023-02-17 02:41:32.307
601    2047000004  1676653026683  57.224  26.630 2023-02-17 02:41:33.337
600    2047000004  1676653027440  56.862  25.804 2023-02-17 02:41:34.094
599    2047000004  1676653028466  56.583  25.083 2023-02-17 02:41:35.120
...           ...            ...     ...     ...                     ...
43323  2047000853  1676704730566  14.826  24.904 2023-02-17 17:03:17.220
43322  2047000853  1676704731466  15.877  24.502 2023-02-17 17:03:18.120
43321  2047000853  1676704734496  13.581  24.484 2023-02-17 17:03:21.150
43320  2047000853  1676704736493  14.743  24.367 2023-02-17 17:03:23.147
43319  2047000853  1676704737496  15.904  24.266 2023-02-17 17:03:24.150

         area  idTblLoc  path_id
603     111.0         3        1
602     111.0         3        1
601     111.0         3        1
600    1363.0         3        1
599    1363.0         3        1
...       ...       ...      ...
43323   111.0         3     2847
43322   111.0         3     2847
43321   111.0         3     2847
43320   111.0         3     2847
43319   111.0         3     2847

[44680 rows x 8 columns]

In [109]:
df_filtered.to_csv('bss19.csv', index=False)

In [110]:
start_time = '2023-02-18'
end_time = '2023-02-19'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

     DeviceId      Timestamp       X       Y                Datetime   area  \
1  2047000297  1676744325270  21.684  28.430 2023-02-18 04:03:11.924  111.0
0  2047000297  1676744347483  20.517  29.808 2023-02-18 04:03:34.137  111.0

   idTblLoc  path_id
1         3        1
0         3        1

In [111]:
df_filtered.to_csv('bss20.csv', index=False)

In [118]:
start_time = '2023-02-13'
end_time = '2023-02-14'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364 and trigger == True:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
3312   2047000012  1676305212110  57.214  30.172 2023-02-13 02:04:38.764
3311   2047000012  1676305212850  56.758  29.876 2023-02-13 02:04:39.504
3310   2047000012  1676305214866  57.302  28.962 2023-02-13 02:04:41.520
3309   2047000012  1676305215906  57.607  28.433 2023-02-13 02:04:42.560
3308   2047000012  1676305216903  57.687  27.921 2023-02-13 02:04:43.557
...           ...            ...     ...     ...                     ...
61401  2047000853  1676378743986  14.420  18.443 2023-02-13 22:30:10.640
61400  2047000853  1676378745003  13.031  17.879 2023-02-13 22:30:11.657
61399  2047000853  1676378751466  12.874  17.633 2023-02-13 22:30:18.120
61398  2047000853  1676378811696  10.461  16.870 2023-02-13 22:31:18.350
61397  2047000853  1676378812720  10.885  15.075 2023-02-13 22:31:19.374

        area  idTblLoc  path_id
3312   111.0         3        1
3311   111.0         3        1
3310   111.0         3        1
3309   111.0         3        1
3308   111.0         3        1
...      ...       ...      ...
61401  111.0         3      185
61400  111.0         3      185
61399  111.0         3      185
61398  111.0         3      185
61397  111.0         3      185

[61541 rows x 8 columns]

In [119]:
df_filtered.to_csv('testbss1.csv', index=False)

In [115]:
start_time = '2023-02-15'
end_time = '2023-02-16'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False

for i, row in df_filtered.iterrows():

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364 and trigger == True:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
2399   2047000012  1676540067670  57.114  28.216 2023-02-15 19:18:54.324
2398   2047000012  1676540068696  57.650  27.832 2023-02-15 19:18:55.350
2397   2047000012  1676540070470  57.733  27.200 2023-02-15 19:18:57.124
2396   2047000012  1676540071980  57.222  26.080 2023-02-15 19:18:58.634
2395   2047000012  1676540073796  56.870  25.449 2023-02-15 19:19:00.450
...           ...            ...     ...     ...                     ...
63053  2047000853  1676556913413  33.923  12.014 2023-02-15 23:59:40.067
63052  2047000853  1676556916440  33.804  12.506 2023-02-15 23:59:43.094
63051  2047000853  1676556921473  33.863  11.785 2023-02-15 23:59:48.127
63050  2047000853  1676556923516  33.601  13.035 2023-02-15 23:59:50.170
63049  2047000853  1676556926520  33.352  13.556 2023-02-15 23:59:53.174

         area  idTblLoc  path_id
2399    111.0         3        1
2398    111.0         3        1
2397    111.0         3        1
2396   1363.0         3        1
2395   1363.0         3        1
...       ...       ...      ...
63053   111.0         3      206
63052   111.0         3      206
63051   111.0         3      206
63050   111.0         3      206
63049   111.0         3      206

[64356 rows x 8 columns]

In [116]:
df_filtered.to_csv('testbss2.csv', index=False)

In [121]:
start_time = '2023-02-15'
end_time = '2023-02-16'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

df_filtered['path_id'] = 1
pathid_counter = 1
trigger = False
prev_device_id = None

for i, row in df_filtered.iterrows():
    
    curr_device_id = row['DeviceId']

    if curr_device_id != prev_device_id:
        pathid_counter = 1
        trigger = False

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364 and trigger == True:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
    
    prev_device_id = curr_device_id

print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
2399   2047000012  1676540067670  57.114  28.216 2023-02-15 19:18:54.324
2398   2047000012  1676540068696  57.650  27.832 2023-02-15 19:18:55.350
2397   2047000012  1676540070470  57.733  27.200 2023-02-15 19:18:57.124
2396   2047000012  1676540071980  57.222  26.080 2023-02-15 19:18:58.634
2395   2047000012  1676540073796  56.870  25.449 2023-02-15 19:19:00.450
...           ...            ...     ...     ...                     ...
63053  2047000853  1676556913413  33.923  12.014 2023-02-15 23:59:40.067
63052  2047000853  1676556916440  33.804  12.506 2023-02-15 23:59:43.094
63051  2047000853  1676556921473  33.863  11.785 2023-02-15 23:59:48.127
63050  2047000853  1676556923516  33.601  13.035 2023-02-15 23:59:50.170
63049  2047000853  1676556926520  33.352  13.556 2023-02-15 23:59:53.174

         area  idTblLoc  path_id
2399    111.0         3        1
2398    111.0         3        1
2397    111.0         3        1
2396   1363.0         3        1
2395   1363.0         3        1
...       ...       ...      ...
63053   111.0         3        4
63052   111.0         3        4
63051   111.0         3        4
63050   111.0         3        4
63049   111.0         3        4

[64356 rows x 8 columns]

In [122]:
df_filtered.to_csv('testbss3.csv', index=False)

In [123]:
start_time = '2023-02-17'
end_time = '2023-02-18'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'])

pathid_counters = {}
for device_id in df_filtered['DeviceId'].unique():
    pathid_counters[device_id] = 1

df_filtered['path_id'] = 1

for i, row in df_filtered.iterrows():

    device_id = row['DeviceId']
    pathid_counter = pathid_counters[device_id]

    if row['area'] == 1363:
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counters[device_id] += 1
        df_filtered.loc[i, 'path_id'] = pathid_counters[device_id]
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
603    2047000004  1676653022986  57.097  30.224 2023-02-17 02:41:29.640
602    2047000004  1676653025653  57.293  28.114 2023-02-17 02:41:32.307
601    2047000004  1676653026683  57.224  26.630 2023-02-17 02:41:33.337
600    2047000004  1676653027440  56.862  25.804 2023-02-17 02:41:34.094
599    2047000004  1676653028466  56.583  25.083 2023-02-17 02:41:35.120
...           ...            ...     ...     ...                     ...
43323  2047000853  1676704730566  14.826  24.904 2023-02-17 17:03:17.220
43322  2047000853  1676704731466  15.877  24.502 2023-02-17 17:03:18.120
43321  2047000853  1676704734496  13.581  24.484 2023-02-17 17:03:21.150
43320  2047000853  1676704736493  14.743  24.367 2023-02-17 17:03:23.147
43319  2047000853  1676704737496  15.904  24.266 2023-02-17 17:03:24.150

         area  idTblLoc  path_id
603     111.0         3        1
602     111.0         3        1
601     111.0         3        1
600    1363.0         3        1
599    1363.0         3        1
...       ...       ...      ...
43323   111.0         3       66
43322   111.0         3       66
43321   111.0         3       66
43320   111.0         3       66
43319   111.0         3       66

[44680 rows x 8 columns]

In [124]:
df_filtered.to_csv('testbss4.csv', index=False)

In [125]:
start_time = '2023-02-17'
end_time = '2023-02-18'

df_filtered = df[(df['Datetime'] >= start_time) & (df['Datetime'] <= end_time)].reset_index(drop=True)

df_filtered = df_filtered.sort_values(by=['DeviceId', 'Datetime'], ascending=[True, True])

df_filtered['path_id'] = 1
pathid_counter = 1
device_id = None
trigger = False

for i, row in df_filtered.iterrows():

    if row['DeviceId'] != device_id:
        device_id = row['DeviceId']
        pathid_counter = 1
        trigger = False

    if row['area'] == 1363:
        trigger = True
        df_filtered.loc[i, 'path_id'] = pathid_counter
    elif row['area'] == 1364:
        pathid_counter += 1
        trigger = False
        df_filtered.loc[i, 'path_id'] = pathid_counter
    else:
        df_filtered.loc[i, 'path_id'] = pathid_counter
        
print(df_filtered)

         DeviceId      Timestamp       X       Y                Datetime  \
603    2047000004  1676653022986  57.097  30.224 2023-02-17 02:41:29.640
602    2047000004  1676653025653  57.293  28.114 2023-02-17 02:41:32.307
601    2047000004  1676653026683  57.224  26.630 2023-02-17 02:41:33.337
600    2047000004  1676653027440  56.862  25.804 2023-02-17 02:41:34.094
599    2047000004  1676653028466  56.583  25.083 2023-02-17 02:41:35.120
...           ...            ...     ...     ...                     ...
43323  2047000853  1676704730566  14.826  24.904 2023-02-17 17:03:17.220
43322  2047000853  1676704731466  15.877  24.502 2023-02-17 17:03:18.120
43321  2047000853  1676704734496  13.581  24.484 2023-02-17 17:03:21.150
43320  2047000853  1676704736493  14.743  24.367 2023-02-17 17:03:23.147
43319  2047000853  1676704737496  15.904  24.266 2023-02-17 17:03:24.150

         area  idTblLoc  path_id
603     111.0         3        1
602     111.0         3        1
601     111.0         3        1
600    1363.0         3        1
599    1363.0         3        1
...       ...       ...      ...
43323   111.0         3       66
43322   111.0         3       66
43321   111.0         3       66
43320   111.0         3       66
43319   111.0         3       66

[44680 rows x 8 columns]